version: '3.1'

volumes:
  database_data:
    driver: local

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:docker-dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    network_mode: "host"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/survey
      GOOGLE_APPLICATION_CREDENTIALS: service-account.json


  postgres:
    image: postgres:12.1-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cristiano007
      POSTGRES_DB: survey

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

