# Use postgres/example user/password credentials
version: '3.1'

services:

  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/survey

  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cristiano007
      POSTGRES_DB: survey

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    driver: bridge
